export const ADD_COMMENT="ADD_COMMENT";
export const GET_COMMENTS="GET_COMMENTS";
export const GET_REEL_COMMENTS="GET_REEL_COMMENTS";
export const LIKE_COMMENT="LIKE_COMMENT";
export const UNLIKE_COMMENT="UNLIKE_COMMENT";